
package com.stellent.dev.docinfo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocInfo", targetNamespace = "http://www.stellent.com/DocInfo/", wsdlLocation = "file:/Users/ryancarlson/Projects/dss-middleware/src/main/resources/wsdl/dev/DocInfo.wsdl")
public class DocInfo
    extends Service
{

    private final static URL DOCINFO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.stellent.dev.docinfo.DocInfo.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.stellent.dev.docinfo.DocInfo.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/ryancarlson/Projects/dss-middleware/src/main/resources/wsdl/dev/DocInfo.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/ryancarlson/Projects/dss-middleware/src/main/resources/wsdl/dev/DocInfo.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCINFO_WSDL_LOCATION = url;
    }

    public DocInfo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocInfo() {
        super(DOCINFO_WSDL_LOCATION, new QName("http://www.stellent.com/DocInfo/", "DocInfo"));
    }

    /**
     * 
     * @return
     *     returns DocInfoSoap
     */
    @WebEndpoint(name = "DocInfoSoap")
    public DocInfoSoap getDocInfoSoap() {
        return super.getPort(new QName("http://www.stellent.com/DocInfo/", "DocInfoSoap"), DocInfoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocInfoSoap
     */
    @WebEndpoint(name = "DocInfoSoap")
    public DocInfoSoap getDocInfoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.stellent.com/DocInfo/", "DocInfoSoap"), DocInfoSoap.class, features);
    }

}
