
package com.stellent.dev.search;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Search", targetNamespace = "http://www.stellent.com/Search/", wsdlLocation = "file:/Users/ryancarlson/Projects/dss-middleware/src/main/resources/wsdl/dev/Search.wsdl")
public class Search
    extends Service
{

    private final static URL SEARCH_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.stellent.dev.search.Search.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.stellent.dev.search.Search.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/ryancarlson/Projects/dss-middleware/src/main/resources/wsdl/dev/Search.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/ryancarlson/Projects/dss-middleware/src/main/resources/wsdl/dev/Search.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SEARCH_WSDL_LOCATION = url;
    }

    public Search(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Search() {
        super(SEARCH_WSDL_LOCATION, new QName("http://www.stellent.com/Search/", "Search"));
    }

    /**
     * 
     * @return
     *     returns SearchSoap
     */
    @WebEndpoint(name = "SearchSoap")
    public SearchSoap getSearchSoap() {
        return super.getPort(new QName("http://www.stellent.com/Search/", "SearchSoap"), SearchSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchSoap
     */
    @WebEndpoint(name = "SearchSoap")
    public SearchSoap getSearchSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.stellent.com/Search/", "SearchSoap"), SearchSoap.class, features);
    }

}
