
package com.stellent.dev.metadata;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MetaData", targetNamespace = "http://www.stellent.com/MetaData/", wsdlLocation = "file:/Users/ryancarlson/Projects/dss-middleware/src/main/resources/wsdl/dev/MetaData.wsdl")
public class MetaData
    extends Service
{

    private final static URL METADATA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.stellent.dev.metadata.MetaData.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.stellent.dev.metadata.MetaData.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/ryancarlson/Projects/dss-middleware/src/main/resources/wsdl/dev/MetaData.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/ryancarlson/Projects/dss-middleware/src/main/resources/wsdl/dev/MetaData.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        METADATA_WSDL_LOCATION = url;
    }

    public MetaData(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MetaData() {
        super(METADATA_WSDL_LOCATION, new QName("http://www.stellent.com/MetaData/", "MetaData"));
    }

    /**
     * 
     * @return
     *     returns MetaDataSoap
     */
    @WebEndpoint(name = "MetaDataSoap")
    public MetaDataSoap getMetaDataSoap() {
        return super.getPort(new QName("http://www.stellent.com/MetaData/", "MetaDataSoap"), MetaDataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MetaDataSoap
     */
    @WebEndpoint(name = "MetaDataSoap")
    public MetaDataSoap getMetaDataSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.stellent.com/MetaData/", "MetaDataSoap"), MetaDataSoap.class, features);
    }

}
