
package com.stellent.dev.metadata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MetaDataSoap", targetNamespace = "http://www.stellent.com/MetaData/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MetaDataSoap {


    /**
     * 
     * @param extraProps
     * @param privilege
     * @return
     *     returns com.stellent.dev.metadata.DocMetaDataResult
     */
    @WebMethod(operationName = "DocMetaData", action = "http://www.stellent.com/MetaData/")
    @WebResult(name = "DocMetaDataResult", targetNamespace = "http://www.stellent.com/MetaData/")
    @RequestWrapper(localName = "DocMetaData", targetNamespace = "http://www.stellent.com/MetaData/", className = "com.stellent.dev.metadata.DocMetaData")
    @ResponseWrapper(localName = "DocMetaDataResponse", targetNamespace = "http://www.stellent.com/MetaData/", className = "com.stellent.dev.metadata.DocMetaDataResponse")
    public DocMetaDataResult docMetaData(
        @WebParam(name = "privilege", targetNamespace = "http://www.stellent.com/MetaData/")
        Integer privilege,
        @WebParam(name = "extraProps", targetNamespace = "http://www.stellent.com/MetaData/")
        IdcPropertyList extraProps);

    /**
     * 
     * @param extraProps
     * @return
     *     returns com.stellent.dev.metadata.UserMetaDataResult
     */
    @WebMethod(operationName = "UserMetaData", action = "http://www.stellent.com/MetaData/")
    @WebResult(name = "UserMetaDataResult", targetNamespace = "http://www.stellent.com/MetaData/")
    @RequestWrapper(localName = "UserMetaData", targetNamespace = "http://www.stellent.com/MetaData/", className = "com.stellent.dev.metadata.UserMetaData")
    @ResponseWrapper(localName = "UserMetaDataResponse", targetNamespace = "http://www.stellent.com/MetaData/", className = "com.stellent.dev.metadata.UserMetaDataResponse")
    public UserMetaDataResult userMetaData(
        @WebParam(name = "extraProps", targetNamespace = "http://www.stellent.com/MetaData/")
        IdcPropertyList extraProps);

}
