
package com.stellent.dev.getfile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GetFileSoap", targetNamespace = "http://www.stellent.com/GetFile/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetFileSoap {


    /**
     * 
     * @param dID
     * @param extraProps
     * @param rendition
     * @return
     *     returns com.stellent.dev.getfile.GetFileByIDResult
     */
    @WebMethod(operationName = "GetFileByID", action = "http://www.stellent.com/GetFile/")
    @WebResult(name = "GetFileByIDResult", targetNamespace = "http://www.stellent.com/GetFile/")
    @RequestWrapper(localName = "GetFileByID", targetNamespace = "http://www.stellent.com/GetFile/", className = "com.stellent.dev.getfile.GetFileByID")
    @ResponseWrapper(localName = "GetFileByIDResponse", targetNamespace = "http://www.stellent.com/GetFile/", className = "com.stellent.dev.getfile.GetFileByIDResponse")
    public GetFileByIDResult getFileByID(
        @WebParam(name = "dID", targetNamespace = "http://www.stellent.com/GetFile/")
        Integer dID,
        @WebParam(name = "rendition", targetNamespace = "http://www.stellent.com/GetFile/")
        String rendition,
        @WebParam(name = "extraProps", targetNamespace = "http://www.stellent.com/GetFile/")
        IdcPropertyList extraProps);

    /**
     * 
     * @param extraProps
     * @param revisionSelectionMethod
     * @param rendition
     * @param dDocName
     * @return
     *     returns com.stellent.dev.getfile.GetFileByNameResult
     */
    @WebMethod(operationName = "GetFileByName", action = "http://www.stellent.com/GetFile/")
    @WebResult(name = "GetFileByNameResult", targetNamespace = "http://www.stellent.com/GetFile/")
    @RequestWrapper(localName = "GetFileByName", targetNamespace = "http://www.stellent.com/GetFile/", className = "com.stellent.dev.getfile.GetFileByName")
    @ResponseWrapper(localName = "GetFileByNameResponse", targetNamespace = "http://www.stellent.com/GetFile/", className = "com.stellent.dev.getfile.GetFileByNameResponse")
    public GetFileByNameResult getFileByName(
        @WebParam(name = "dDocName", targetNamespace = "http://www.stellent.com/GetFile/")
        String dDocName,
        @WebParam(name = "revisionSelectionMethod", targetNamespace = "http://www.stellent.com/GetFile/")
        String revisionSelectionMethod,
        @WebParam(name = "rendition", targetNamespace = "http://www.stellent.com/GetFile/")
        String rendition,
        @WebParam(name = "extraProps", targetNamespace = "http://www.stellent.com/GetFile/")
        IdcPropertyList extraProps);

}
